# Generated by Django 5.2.14 on 2026-05-28 16:54

import app_modules.quiz.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Неверный формат телефона')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='access_token',
            field=models.CharField(db_index=True, default=app_modules.quiz.models.generate_token, max_length=64, unique=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название'),
        ),
    ]
