# Generated by Django 6.0.3 on 2026-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
