# Generated by Django 6.0.3 on 2026-05-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0003_alter_user_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_token',
        ),
        migrations.AddField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Таймер в секундах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='quiz_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='quiz_user_set', to='auth.permission'),
        ),
    ]
