# Generated by Django 6.0.3 on 2026-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_user_jwt_token_quiz_timer_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор')], default='single', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
