# Generated by Django 6.0.3 on 2026-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=100, verbose_name='Баллов за правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='timer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Таймер на вопрос в секундах'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points_per_question',
            field=models.IntegerField(default=100, verbose_name='Баллов за правильный ответ'),
        ),
    ]
