# Generated by Django 6.0.3 on 2026-05-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participantanswer',
            table='participant_answer_new',
        ),
        migrations.AlterModelTable(
            name='quizsession',
            table='quiz_session_new',
        ),
    ]
