# Generated by Django 6.0.3 on 2026-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_user_phone_alter_quiz_access_token_alter_quiz_title'),
        ('quiz_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='quizsession',
            unique_together={('quiz', 'participant_name', 'is_completed')},
        ),
    ]
