# Generated by Django 6.0.5 on 2026-05-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sessions', '0002_participantanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='participant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
